name: Generate Snake Animation

on:
  schedule:
    # Runs every 12 hours
    - cron: "0 */12 * * *"
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest
    permissions:
      contents: write # IMPORTANT: Needs permission to push the file to the repo
    
    steps:
      - uses: actions/checkout@v3
      
      # Generates the snake SVG file
      - uses: Platane/snk@v3
        id: snake-gif
        with:
          github_user_name: ${{ github.repository_owner }}
          outputs: dist/github-snake.svg
          
      # Pushes the generated snake image back to the repository
      - uses: crazy-max/ghaction-github-pages@v3
        with:
          target_branch: output # Creates a new branch named 'output' to store the SVG
          build_dir: dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
